server:
  port: 8084
# Application Name

# -- Application Configuration --
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # File URI - Adjust path according to your system:
          # Windows: file:///C:/Users/YourUser/microservices-lab1/config-repo
          #uri: file://${user.home}/IdeaProjects/config-repo
          uri: C:/Users/edgar/IdeaProjects/config-repo

          # Git Configuration
          default-label: main